name: Raul_Practica_Github_Actions_workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linter_job:
    name: Linter_job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install deps (prefer lockfile)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Verify lint script exists
        run: |
          node -e "const p=require('./package.json'); if(!p.scripts?.lint){console.error('No hay script \"lint\" en package.json'); process.exit(2)}; console.log('lint script:', p.scripts.lint)"

      - name: Run linter (fail on warnings)
        run: npm run lint -- --max-warnings=0

          cypress_job:
    name: Cypress_job
    runs-on: ubuntu-latest
    needs: [ linter_job ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (Next.js)
        run: npm run build

      - name: Run Cypress tests (continues on error)
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: http://localhost:3000
          browser: chrome
          config: baseUrl=http://localhost:3000
        continue-on-error: true

      - name: Write result summary to result.txt
        run: |
          echo "${{ steps.cypress.outcome }}" > result.txt
          echo "Cypress outcome: ${{ steps.cypress.outcome }}"

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-result
          path: result.txt